name: Pester
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
jobs:
  test-pwsh:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run Pester with CodeCoverage
      run: |
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -MinimumVersion 5.1 -confirm:$false -Force
        $config = New-PesterConfiguration
        $config.CodeCoverage.Enabled = $true
        Invoke-Pester -Configuration $config
      shell: pwsh
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
